on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: MarshallOfSound/gh-act-test@320a38bfd573a2ca3a1fc38be8532508f828c45f
